// Sabine
// Configuration File
//---------------------------------------------------------------------------

// IP to bind the server to
web_bind_ip: 0.0.0.0

// Ports to listen for connections on. You can specify multiple ones,
// for easier switching between clients that might use different ports
// by default, such as Alpha (7000) or newer ones (6900).
web_bind_ports: 5614

include "/user/conf/web.conf"
