// Sabine
// Configuration File
//---------------------------------------------------------------------------

// Basic Skills are required for storage, etc...?
// Options:
//   true = Basic Skill is required
//   false = Basic Skill is not required
basic_skill_check: true

include "/user/conf/world/skills.conf"
