using System;
using System.Threading.Tasks;
using Sabine.Shared.Const;
using Sabine.Shared.Util;
using Sabine.Shared.World;
using Sabine.Zone.Network;
using Sabine.Zone.Skills;
using Sabine.Zone.World.Actors;
using Yggdrasil.Logging;
using Yggdrasil.Util.Commands;

namespace Sabine.Zone.Commands
{
	public partial class ChatCommands
	{
		private void LoadDebug()
		{
			this.Add("test", "", Localization.Get("Behaviour undefined."), this.Test);
			this.Add("debugpath", "", Localization.Get("Toggles path debugging on and off."), this.DebugPath);
			this.Add("debugmode", "", Localization.Get("Toggles debug mode."), this.DebugMode);
			this.Add("mapflag", "<flag> [on|off]", Localization.Get("Reads or toggles a map flag."), this.MapFlag);
		}

		/// <summary>
		/// Test command that may be used to test code. Don't ever commit
		/// changes to this command!
		/// </summary>
		private CommandResult Test(PlayerCharacter sender, PlayerCharacter target, string message, string commandName, Arguments args)
		{
			Log.Debug("Hello, test!");

			if (Enum.TryParse<SkillId>(args.Get(0), out var skillId))
				sender.Skills.Add(skillId, 1, SkillPerm.Temporary);

			return CommandResult.Okay;
		}

		/// <summary>
		/// Toggles path debugging on and off.
		/// </summary>
		private CommandResult DebugPath(PlayerCharacter sender, PlayerCharacter target, string message, string commandName, Arguments args)
		{
			// This makes the character move between two specific positions
			// in Prontera South, where the client's path and the one
			// generated by our path finder currently diverge. Leaving
			// this here for testing purposes until it's fixed.
			if (args.Count != 0 && args.Get(0) == "test")
			{
				if (sender.Map.StringId != "prt_vilg01")
				{
					sender.ServerMessage("Go to prt_vilg01 first.");
					return CommandResult.Okay;
				}

				var fromPos = new Position(108, 92);
				var toPos = new Position(111, 86);

				sender.Warp(sender.MapId, fromPos);

				Task.Delay(2000).ContinueWith(_ =>
				{
					Send.ZC_NOTIFY_PLAYERMOVE(sender, fromPos, toPos);

					var path = sender.Map.PathFinder.FindPath(fromPos, toPos);
					foreach (var pathPos in path)
					{
						var npc = new Npc(IdentityId.JT_1_F_01);
						npc.Warp(sender.Map.Id, pathPos);

						Task.Delay(3000).ContinueWith(__ => sender.Map.RemoveNpc(npc));
					}
				});

				return CommandResult.Okay;
			}

			var enabled = target.Vars.Temp.ToggleBool("Sabine.DebugPathEnabled");

			if (enabled)
				sender.ServerMessage(Localization.Get("Path debugging is now enabled."));
			else
				sender.ServerMessage(Localization.Get("Path debugging is now disabled."));

			return CommandResult.Okay;
		}

		/// <summary>
		/// Toggles debug mode on and off, enabling debug messages for
		/// testing during development.
		/// </summary>
		private CommandResult DebugMode(PlayerCharacter sender, PlayerCharacter target, string message, string commandName, Arguments args)
		{
			var enabled = target.Vars.Temp.ToggleBool("Sabine.DebugMode");

			if (enabled)
				sender.ServerMessage(Localization.Get("Debug mode is enabled."));
			else
				sender.ServerMessage(Localization.Get("Debug mode is disabled."));

			return CommandResult.Okay;
		}

		private CommandResult MapFlag(PlayerCharacter sender, PlayerCharacter target, string message, string commandName, Arguments args)
		{
			if (args.Count == 0)
			{
				sender.ServerMessage("Map {0} flags: {1}", target.Map.StringId, target.Map.Flags);
				return CommandResult.Okay;
			}

			if (!Enum.TryParse<Sabine.Zone.World.Maps.MapFlags>(args.Get(0), true, out var flag))
				return CommandResult.InvalidArgument;

			var on = args.Count >= 2 ? args.Get(1) == "on" || args.Get(1) == "1" : !target.Map.HasFlag(flag);
			if (on) target.Map.SetFlag(flag); else target.Map.ClearFlag(flag);
			sender.ServerMessage("{0} {1} on {2}.", flag, on ? "set" : "cleared", target.Map.StringId);
			return CommandResult.Okay;
		}
	}
}
