using System;
using System.Threading.Tasks;
using Sabine.Shared.Const;
using Sabine.Shared.Util;
using Sabine.Shared.World;
using Sabine.Zone.Network;
using Sabine.Zone.Skills;
using Sabine.Zone.World.Actors;
using Yggdrasil.Logging;
using Yggdrasil.Util.Commands;

namespace Sabine.Zone.Commands
{
	public partial class ChatCommands
	{
		private void LoadDebug()
		{
			this.Add("test", "", Localization.Get("Behaviour undefined."), this.Test);
			this.Add("debugpath", "", Localization.Get("Toggles path debugging on and off."), this.DebugPath);
			this.Add("debugmode", "", Localization.Get("Toggles debug mode."), this.DebugMode);
			this.Add("mapflag", "<flag> [on|off]", Localization.Get("Reads or toggles a map flag."), this.MapFlag);
			this.Add("persistencetest", "", Localization.Get("Saves the target, reloads them, and reports diffs in body/cart/storage."), this.PersistenceTest);
		}

		/// <summary>
		/// Test command that may be used to test code. Don't ever commit
		/// changes to this command!
		/// </summary>
		private CommandResult Test(PlayerCharacter sender, PlayerCharacter target, string message, string commandName, Arguments args)
		{
			Log.Debug("Hello, test!");

			if (Enum.TryParse<SkillId>(args.Get(0), out var skillId))
				sender.Skills.Add(skillId, 1, SkillPerm.Temporary);

			return CommandResult.Okay;
		}

		/// <summary>
		/// Toggles path debugging on and off.
		/// </summary>
		private CommandResult DebugPath(PlayerCharacter sender, PlayerCharacter target, string message, string commandName, Arguments args)
		{
			// This makes the character move between two specific positions
			// in Prontera South, where the client's path and the one
			// generated by our path finder currently diverge. Leaving
			// this here for testing purposes until it's fixed.
			if (args.Count != 0 && args.Get(0) == "test")
			{
				if (sender.Map.StringId != "prt_vilg01")
				{
					sender.ServerMessage("Go to prt_vilg01 first.");
					return CommandResult.Okay;
				}

				var fromPos = new Position(108, 92);
				var toPos = new Position(111, 86);

				sender.Warp(sender.MapId, fromPos);

				Task.Delay(2000).ContinueWith(_ =>
				{
					Send.ZC_NOTIFY_PLAYERMOVE(sender, fromPos, toPos);

					var path = sender.Map.PathFinder.FindPath(fromPos, toPos);
					foreach (var pathPos in path)
					{
						var npc = new Npc(IdentityId.JT_1_F_01);
						npc.Warp(sender.Map.Id, pathPos);

						Task.Delay(3000).ContinueWith(__ => sender.Map.RemoveNpc(npc));
					}
				});

				return CommandResult.Okay;
			}

			var enabled = target.Vars.Temp.ToggleBool("Sabine.DebugPathEnabled");

			if (enabled)
				sender.ServerMessage(Localization.Get("Path debugging is now enabled."));
			else
				sender.ServerMessage(Localization.Get("Path debugging is now disabled."));

			return CommandResult.Okay;
		}

		/// <summary>
		/// Toggles debug mode on and off, enabling debug messages for
		/// testing during development.
		/// </summary>
		private CommandResult DebugMode(PlayerCharacter sender, PlayerCharacter target, string message, string commandName, Arguments args)
		{
			var enabled = target.Vars.Temp.ToggleBool("Sabine.DebugMode");

			if (enabled)
				sender.ServerMessage(Localization.Get("Debug mode is enabled."));
			else
				sender.ServerMessage(Localization.Get("Debug mode is disabled."));

			return CommandResult.Okay;
		}

		private CommandResult MapFlag(PlayerCharacter sender, PlayerCharacter target, string message, string commandName, Arguments args)
		{
			if (args.Count == 0)
			{
				sender.ServerMessage("Map {0} flags: {1}", target.Map.StringId, target.Map.Flags);
				return CommandResult.Okay;
			}

			if (!Enum.TryParse<Sabine.Zone.World.Maps.MapFlags>(args.Get(0), true, out var flag))
				return CommandResult.InvalidArgument;

			var on = args.Count >= 2 ? args.Get(1) == "on" || args.Get(1) == "1" : !target.Map.HasFlag(flag);
			if (on) target.Map.SetFlag(flag); else target.Map.ClearFlag(flag);
			sender.ServerMessage("{0} {1} on {2}.", flag, on ? "set" : "cleared", target.Map.StringId);
			return CommandResult.Okay;
		}

		/// <summary>
		/// Saves the target's current state, reloads it from the database
		/// into a throwaway character, and diffs body/cart/storage to verify
		/// persistence end-to-end. The reloaded character is discarded; the
		/// live target is unaffected.
		/// </summary>
		private CommandResult PersistenceTest(PlayerCharacter sender, PlayerCharacter target, string message, string commandName, Arguments args)
		{
			static System.Collections.Generic.Dictionary<int, int> Aggregate(System.Collections.Generic.IEnumerable<Item> items)
			{
				var dict = new System.Collections.Generic.Dictionary<int, int>();
				foreach (var item in items)
				{
					if (!dict.TryGetValue(item.ClassId, out var amount))
						amount = 0;
					dict[item.ClassId] = amount + item.Amount;
				}
				return dict;
			}

			static string Diff(System.Collections.Generic.Dictionary<int, int> before, System.Collections.Generic.Dictionary<int, int> after)
			{
				var sb = new System.Text.StringBuilder();
				foreach (var (cls, amt) in before)
				{
					if (!after.TryGetValue(cls, out var got) || got != amt)
						sb.Append($" missing {cls}x{amt}(got{got});");
				}
				foreach (var (cls, amt) in after)
				{
					if (!before.ContainsKey(cls))
						sb.Append($" extra {cls}x{amt};");
				}
				return sb.Length == 0 ? "OK" : sb.ToString().Trim();
			}

			var account = target.Connection.Account;

			var bodyBefore = Aggregate(target.Inventory.GetItems());
			var cartBefore = Aggregate(target.Inventory.GetCartItems());
			var storageBefore = Aggregate(target.Storage.GetItems());

			try
			{
				ZoneServer.Instance.Database.SaveCharacter(account, target);
			}
			catch (Exception ex)
			{
				sender.ServerMessage("PersistenceTest: SaveCharacter threw: {0}", ex.Message);
				return CommandResult.Okay;
			}

			PlayerCharacter reloaded;
			try
			{
				reloaded = ZoneServer.Instance.Database.GetCharacter(account, target.Id);
			}
			catch (Exception ex)
			{
				sender.ServerMessage("PersistenceTest: GetCharacter threw: {0}", ex.Message);
				return CommandResult.Okay;
			}

			var bodyAfter = Aggregate(reloaded.Inventory.GetItems());
			var cartAfter = Aggregate(reloaded.Inventory.GetCartItems());
			var storageAfter = Aggregate(reloaded.Storage.GetItems());

			sender.ServerMessage("PersistenceTest for {0}:", target.Name);
			sender.ServerMessage("- body  ({0} -> {1} stacks): {2}", bodyBefore.Count, bodyAfter.Count, Diff(bodyBefore, bodyAfter));
			sender.ServerMessage("- cart  ({0} -> {1} stacks): {2}", cartBefore.Count, cartAfter.Count, Diff(cartBefore, cartAfter));
			sender.ServerMessage("- store ({0} -> {1} stacks): {2}", storageBefore.Count, storageAfter.Count, Diff(storageBefore, storageAfter));

			return CommandResult.Okay;
		}
	}
}
